[package]
name = "mqtt4hwinfo"
version = "0.0.0"
edition = "2024"
license = "MIT"
description = "Add MQTT topics as sensors for display in HWiNFO"
repository = "https://github.com/travis-fm/mqtt4hwinfo"

[dependencies]
