[broker]
# Host or IP of the MQTT broker
host = "localhost"
# Port to use for connection (optional, will use 1883 as default)
port = 1883
# Username and password for authentication (optional, remove for anonymous access)
username = "test-account"
password = "abc123"


# Each device goes into a [[devices]] block, where display_name is the device name sensors will show under in HWiNFO
[[devices]]
display_name = "My Custom Device"

# Each sensor for the above device goes into a [[devices.sensors]] block, where display_name is the name of the sensor as shown in HWiNFO
[[devices.sensors]]
display_name = "Custom Power Sensor"

# The type of sensor. Can be one of the following:
# Temp
# Volt
# Fan
# Current
# Power
# Clock
# Usage
# Other
sensor_type = "Power"

# The MQTT topic to register for sensor updates.
# The payload should ONLY contain the updated sensor value.
mqtt_topic = "my_custom_device_top/custom_sensor_subtopic"

# Units to display within HWiNFO (optional)
# Only really applicable for "Other" sensor types
unit = "kWh"
